VERSION = '0.2'

TYPE = 'type'
LIBRML = 'libRML'
ITEM = 'item'
ID = 'id'

ACTIONS = 'actions'
RESTRICTIONS = 'restrictions'
PERMISSION = 'permission'
TENANT = 'tenant'
MENTION = 'mention'
SHARE = 'sharealike'
USAGEGUIDE = 'usageguide'
TEMPLATE = 'template'

#XML
XRESTRICTION = 'restriction'
XACTION = 'action'
XPART = 'part'
XGROUP = 'group'
XSUBNET = 'subnet'
XMACHINE = 'machine'

# Fieldnames
SUBNET = 'subnet'
GROUPS = 'groups'
PARTS = 'parts'
MINAGE = 'minage'
INSIDE = 'inside'
OUTSIDE = 'outside'
MACHINES = 'machines'
FROMDATE = 'fromdate'
TODATE = 'todate'
DURATION = 'duration'
COUNT = 'count'
SESSIONS = 'sessions'
WATERMARK = 'watermarkvalue'
COMMERCIAL = 'commercialuse'
NONCOMMERCIAL = 'noncommercialuse'
MAXRES = 'maxresolution'
MAXBIT = 'maxbitrate'
