VERSION = "0.5.0"

TYPE = "type"
LIBRML = "libRML"
ITEM = "item"
ID = "id"

ACTIONS = "actions"
RESTRICTIONS = "restrictions"
PERMISSION = "permission"
TENANT = "tenant"
MENTION = "mention"
SHARE = "sharealike"
USAGEGUIDE = "usageguide"
TEMPLATE = "template"
COPYRIGHT = "copyright"

# XML
NAMESPACE = "http://librml.org/schema"
XACTION = "action"
XRESTRICTION = "restriction"

# Fieldnames
SUBNET = "subnet"
GROUPS = "groups"
PERCENTAGE = "percentage"
MINAGE = "minage"
MAXAGE = "maxage"
INSIDE = "inside"
OUTSIDE = "outside"
FROMDATE = "fromdate"
TODATE = "todate"
MAXDURATION = "maxduration"
COUNT = "count"
SESSIONS = "sessions"
WATERMARK = "watermarkvalue"
COMMERCIAL = "commercialuse"
NONCOMMERCIAL = "noncommercialuse"
MAXRES = "maxresolution"
MAXBIT = "maxbitrate"
MAXDIMENSION = "maxdimension"
AGREEMENTREQ = "required"
